language: node_js
cache: yarn
node_js:
- '9'
script:
- yarn test
- yarn dist
env:
- BASE_URI=/innoq-styleguide
deploy:
- provider: pages
  skip_cleanup: true
  local_dir: dist/site
  github_token:
    secure: ID7CNbzpYpgPiJuFgMVmAPreJCUBqIicMsBpfia6OIzIIhGiywkOUkQqU9P7LC/+53tlXl4C0QERu5tsvaKTBhuADXctIrphr0o7TzK+3Yc3t+wixpa3u0WOkCO66uEJTWRXw3R4idZI3kOdq0ug38ixETWpQhFVMpSi2J1X7qvz6YCWGaPru7qjcOM3LcjLlTYm5vHMD3rxW7gsNyHPwwYpLMC1ZqqEfMax6jtdy1rNKq5ltQQyZkoLd53PhTOGxjAk9sNedVEEEgHaIEswH0Wq1qNIVHFCmTUMHlIqifkiPAlg1yOHSoT0GhZ1MH3c3re2ldh0U80ysI66yBu1WBGYt2a/Oo6jic2odyfLj/Re0y+A7I4XhIvdPDcFPXOqAiR2+9myzHruGp1paM9NEamYEANDDzLPrxsP2ZbvtXRwdsSvmXPoD8Z7SoSbrtywq0x1uSyN/mhoCqFq9auOGGjmG6h1Z4OZUgDjHUEniJU3tOj9Aq3CYWFi/vU6GO4gElFtpObHlkkzQQtKSslwUpqdqJWdGkX6R4HzlFpg9hiEGTtlplM4tlXPT9fVLpEki71z2KYMLfGhk3ZsP9wfIJQFsCLDDqI+fJXDpDGhAi2oD0o/A7urNEK6ma9EMRHTN9sD0BiD/H1ku6fSxBxXWGEfqOPbGzTBwdY77npwCJo=
  on:
    branch: master
- provider: npm
  skip_cleanup: true
  email: mail@robert-glaser.de
  api_key:
    secure: rU1W4ZTxjH73GZhCzdTGFSDnZEEgUTlhzLzHbV+kXdfL8ogUDFKG7GS3FTTgQ7TKjj4ip6vXoBa1fp3oOaOzcu7cgQXhisx1uIrnV1LYfVCYKBmjs/e5pSE0yTqmJFB3ixrwmAhiTYC61JM6jCTkzGejOOQWU6dx/161ZFSZyEv3M8DoUM57T/aoGcwYrqYbA3axhNpcxiLv39SitbN/OBNHYbocUUiocShLdGVA+g12eOscGCIHxbz/TgMEjLHd4dQlnnjklIbEc56Yspn0dDUVfbG7N4p0eTa0u2Q5K2UGDqs/ltTGBsUmInkQQqte/A4qE70kQYVtcHtqFVTJ1Ereh3MFNSnB6pooFkd5zz3lpBtnvQxLQrLT2r8pzq41Nw2l5RnD90heefZNn5clj0zwcN3Ax1D02eOPh0dhKAe4iSvwZrzCV6PjhoYYTxAb1j2Jz875hm8IGKeFSswEwK9/o/uQpmyiNX0Cl+VpXOkvt/UAe3qkE9MQ/pCEoy57STd0VANOebrEhBiHntPZ8Mr4kIT+LAuZAe0AIniH2QBn10rXM5m5hiKAqpJosCqLdjpC8iwRE/juO85oXGkriqOxRGmdT5/Gp6t/3Y0BCLURKtLr0RNcmJ66NxzGtWoM1yW87Kdqn8BQLW5/5kDpFEssSipUAmjDPrMbM/QYP40=
  on:
    tags: true
    repo: innoq/innoq-styleguide
- provider: releases
  skip_cleanup: true
  api_key:
    secure: WSUrEpJZ6TFUQxS2WglW7ys+aky1MRDVWxEc0f6dCFYfqqAxIxKjbYtLPK0I++9AvEX0x63bMXDZJQZHjm3CzJ/s3QsTmpdfHClAZEWx07UdAYWxxqifJhElc7ZUqnN3x1/08XR/HRvH+00+SDbWNPIAcrm2IK7HmaHTouNbN5qv+9ilnrTU3oosW2nIpWoAi2IRhFMGDR4qXmXBGzaTeGTlCfIwNc+tnPdlVaTsKAqkiFSoSii2ju3XuWoNqrARIdL9uPUgSi/2ef1KgNUoFIi8avPGAl3MBupYAzBF0LBRjuqiLRYgAISSzQicGBNIq+6LOoH9wnfnTgFKbOO18CKC+QyQ9YpvZI3fLYfK0Dk8+NHepb4z17u85qli2yrOsymR/FGzovPX4uG23YTIKwyRkeqh+ZmhONEADLcaiRGe278wsBIw9lKxKIhguysjkXIbIFVN5Tg7Jr2I5rRLaEmSDbZbPJWyx45hEghUUZonLHUJrMpsooDSFGfINB16foKk6j8tW/k1N0X4Ac+Nh0bQ7aELLmCFpjRT/v0S71QSye91Izkes49emEGwokMva7QGh4Ja872F1ZvxoLUZQOBv9qX4JnjXwkq4aJQnXPE21DdGfJKy0iFPUJHPmaw1Svhh02iWNGr31MOpYl852gYAzgjzqkeV448m8YHWa8E=
  file: innoq-styleguide-$TRAVIS_TAG.zip
  on:
    tags: true
notifications:
  email: false
  slack:
    rooms:
      - secure: gqcUUAv9Qtm0WNckZqdQqnQXeU7CsLjH1OxFRklj1bZ4qMXNM74YG6LnaEoZsBPUQdoIYq6t1olZhUlg568mtZJ/gGBD+TcVK1NGppcToE4R6Mk8jatqYwBskrtHUYnunmmOFCwkqi6r2y3KMmTzwI4QX8ZkWoJbL+i70517KIT/Ib+X87KhVD5IAzZhrkaCqmnCkOXNjJpHPfPG66/TQydJRNl/9GQ25uQ/2rSYB65Oo06uP4QFLrCkRofs5sR2+kHYnb6VzN3TeyTsXtXvIosdLB0lx3ct4phgN9bkiWOtOl+a10LVkCGXWXqhC6WsyE1fdC7+M5WAdaFEUMv9nChjTBRqlY/xHU5I68d7n+i9T8BfYkgA35BTurXf+zmldoTirp1X+G9Ofj1TgaPwH0UBdc3mkDtbfxJFY/ldT8uBsroIcAqeKCa1zbJHe3niKyI69fqNdE7SXKmbJQyh7vR7BwOPUk7A+4bOifg6xgOIwD0Y1AcxpFykJK4oJnRAqG0nu3jhK+YvQcE4z8gIjNMI5rq7c7qDfkTAjZLdwAiAyBd3l3kBthNCxVV9TeB1ClTHfKWVmIGhsEinLyJDd9YbXmhQqwpZWxQiFHfPol/Or5HOM85JDrO9lzKuFemBu9SKZ66Y712soNKJfPdquF7icIBNaiXF5d+ZnyFJCeE=
    on_success: change
    on_failure: always
